export default {
    SET_USER: 'SET_USER',
    UNSET_USER: 'UNSET_USER',
    LOAD_USER: 'LOAD_USER',
    LOAD_USER_RESP: 'LOAD_USER_RESP',
    CHANGE_OPTION: 'CHANGE_OPTION',
    SAVE_OPTIONS: 'SAVE_OPTIONS',
    LOAD_OPTIONS: 'LOAD_OPTIONS',
    RESET_OPTIONS: 'RESET_OPTIONS',
    LOAD_RELEASES: 'LOAD_RELEASES',
    LOAD_RELEASES_RESP: 'LOAD_RELEASES_RESP',
}
